---
kind: pipeline
name: openaev-tests

steps:
  - name: Runner information
    image: alpine:3.23
    commands:
    - echo DRONE_STAGE_MACHINE ${DRONE_STAGE_MACHINE}

  - name: api-tests
    image: maven:3.9.9-eclipse-temurin-22
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql:5432/openaev
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      ENGINE_URL: http://elastic:9200
      OPENBAS_RABBITMQ_HOSTNAME: rabbitmq
    commands:
      - mvn spotless:check
      - sleep 60
      - mvn clean install -q -DskipTests
      - cd openaev-api
      - mvn test
      - echo "Running coverage validation..."
      - mvn jacoco:check || echo "⚠️ Coverage threshold check ⚠️"
      - cd ../openaev-framework
      - mvn test

  - name: frontend-tests
    image: node:22.21.1-alpine
    commands:
      - cd openaev-front
      - yarn install
      - yarn build
      - yarn check-ts
      - yarn lint
      - yarn i18n-checker
      - NODE_OPTIONS=--max_old_space_size=8192 yarn test

  - name: app-e2e
    image: maven:3.9.9-eclipse-temurin-22
    detach: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql-e2e:5432/openaev
      SPRING_DATASOURCE_USERNAME: openaev
      SPRING_DATASOURCE_PASSWORD: openaev
      MINIO_ENDPOINT: minio-e2e
      MINIO_PORT: 9000
      ENGINE_URL: http://elastic:9200
      MINIO_ACCESS_KEY: minioadmin
      MINIO_ACCESS_SECRET: minioadmin
      OPENAEV_ADMIN_EMAIL: admin@openaev.io
      OPENAEV_ADMIN_PASSWORD: admin
      OPENAEV_ADMIN_TOKEN: 0d17ce9a-f3a8-4c6d-9721-c98dc3dc023f
      OPENAEV_ADMIN_ENCRYPTION_KEY: ThisIsMyUltraSecureEncryptionKey
      OPENAEV_ADMIN_ENCRYPTION_SALT: ilikesaltyfoodnomnom
      SPRING_PROFILES_ACTIVE: ci
      OPENBAS_RABBITMQ_HOSTNAME: rabbitmq-e2e
    commands:
      - apt update && apt install -y gnupg git npm
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      - apt update && apt install -y nodejs
      - npm install --global yarn
      - cd openaev-front
      - yarn install
      - yarn build
      - cd ..
      - mvn install -DskipTests=true
      - java -jar openaev-api/target/openaev-api.jar
    depends_on:
      - api-tests
      - frontend-tests

  - name: frontend-e2e-tests
    image: node:22.21.1
    commands:
      - apt update
      - apt -y install netcat-traditional
      - while ! nc -z app-e2e 8080 ; do sleep 1 ; done
      - cd openaev-front
      - yarn install
      - yarn playwright install --with-deps chromium
      - APP_URL=http://app-e2e:8080 yarn test:e2e
    depends_on:
      - app-e2e

  - name: frontend-api-types
    image: node:22.21.1
    volumes:
      - name: cache-node-frontend-api-types
        path: /drone/src/openaev-front/node_modules
    commands:
      - apt update
      - apt -y install netcat-traditional
      - while ! nc -z app-e2e 8080 ; do sleep 1 ; done
      - cd openaev-front
      - yarn install
      - API_URL=http://app-e2e:8080 yarn generate-types-from-api
      - |
        if git diff --name-only | grep -q './src/utils/api-types.d.ts'; then
          echo "⚠️ Forgot to generate types! Please run 'yarn run generate-types-from-api' before committing."; exit 1;
        fi
    depends_on:
      - app-e2e

  - name: codecov
    image: robertstettner/drone-codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - openaev-api/target/site/jacoco/jacoco.xml
        - openaev-framework/target/site/jacoco/jacoco.xml
    depends_on:
      - api-tests

  - name: build-circleci
    image: curlimages/curl
    commands:
      - curl -X POST --data "branch=$DRONE_COMMIT_BRANCH" https://circleci.com/api/v1.1/project/github/OpenAEV-Platform/openaev/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      branch:
        - master
        - release/*
      event:
        exclude:
          - pull_request
          - tag
    depends_on:
      - api-tests
      - frontend-tests
      - frontend-e2e-tests

  - name: build-circleci-release
    image: curlimages/curl
    commands:
      - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenAEV-Platform/openaev/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      event:
        - tag
    depends_on:
      - api-tests
      - frontend-tests
      - frontend-e2e-tests

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: drone
      channel: notifications
    when:
      status: [ success, failure ]
    depends_on:
      - api-tests
      - frontend-tests
      - frontend-e2e-tests

services:
  - name: minio
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ server, /data ]
  - name: pgsql
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: openaev
      POSTGRES_PASSWORD: openaev
      POSTGRES_DB: openaev
    commands: 
      - docker-entrypoint.sh -c 'max_connections=500'
  - name: rabbitmq
    image: rabbitmq:4.1-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  - name: minio-e2e
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ server, /data ]
  - name: pgsql-e2e
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: openaev
      POSTGRES_PASSWORD: openaev
      POSTGRES_DB: openaev
    commands: 
      - docker-entrypoint.sh -c 'max_connections=500'
  - name: rabbitmq-e2e
    image: rabbitmq:4.1-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  - name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms4g -Xmx4g

image_pull_secrets:
  - dockerconfigjson
